version: 0.2

# AWS CodeBuild buildspec for Colibri Identity Widget
# Builds and deploys to S3/CloudFront for multiple environments

env:
  variables:
    NODE_VERSION: "20"
  parameter-store:
    # Store these in AWS Systems Manager Parameter Store
    # DEV_S3_BUCKET: /colibri/widget/dev/s3-bucket
    # TEST_S3_BUCKET: /colibri/widget/test/s3-bucket
    # STAGE_S3_BUCKET: /colibri/widget/stage/s3-bucket
    # PROD_S3_BUCKET: /colibri/widget/prod/s3-bucket
    # CLOUDFRONT_DISTRIBUTION_ID: /colibri/widget/cloudfront-id

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --legacy-peer-deps
      - echo "Node version:" $(node --version)
      - echo "NPM version:" $(npm --version)

  pre_build:
    commands:
      - echo "Pre-build phase - Linting and validation"
      - npm run lint || true
      - echo "Build started on $(date)"
      - echo "Branch:" $CODEBUILD_WEBHOOK_HEAD_REF
      - echo "Commit:" $CODEBUILD_RESOLVED_SOURCE_VERSION
      
      # Determine environment based on branch
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/main" ]; then
          export DEPLOY_ENV="prod"
          export S3_BUCKET=$PROD_S3_BUCKET
        elif [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/staging" ]; then
          export DEPLOY_ENV="stage"
          export S3_BUCKET=$STAGE_S3_BUCKET
        elif [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/test" ]; then
          export DEPLOY_ENV="test"
          export S3_BUCKET=$TEST_S3_BUCKET
        else
          export DEPLOY_ENV="dev"
          export S3_BUCKET=$DEV_S3_BUCKET
        fi
      - echo "Deploying to environment:" $DEPLOY_ENV
      - echo "S3 Bucket:" $S3_BUCKET

  build:
    commands:
      - echo "Building widget for $DEPLOY_ENV environment..."
      - npm run build:$DEPLOY_ENV
      - echo "Build completed successfully"
      
      # Verify build output
      - ls -lh dist/
      - echo "Widget bundle size:" $(du -h dist/keycloak-widget.umd.js | cut -f1)
      - echo "CSS bundle size:" $(du -h dist/login-widget.css | cut -f1)

  post_build:
    commands:
      - echo "Post-build phase - Deploying to S3"
      
      # Upload to S3 with versioning
      - |
        if [ -z "$S3_BUCKET" ]; then
          echo "ERROR: S3_BUCKET not set for environment $DEPLOY_ENV"
          exit 1
        fi
      
      # Get version from package.json
      - export VERSION=$(node -p "require('./package.json').version")
      - echo "Version:" $VERSION
      
      # Upload versioned files
      - aws s3 cp dist/keycloak-widget.umd.js s3://$S3_BUCKET/auth/v$VERSION/keycloak-widget.umd.js --cache-control "public, max-age=31536000, immutable"
      - aws s3 cp dist/login-widget.css s3://$S3_BUCKET/auth/v$VERSION/login-widget.css --cache-control "public, max-age=31536000, immutable"
      
      # Upload latest (non-versioned) for easy updates
      - aws s3 cp dist/keycloak-widget.umd.js s3://$S3_BUCKET/auth/latest/keycloak-widget.umd.js --cache-control "public, max-age=300"
      - aws s3 cp dist/login-widget.css s3://$S3_BUCKET/auth/latest/login-widget.css --cache-control "public, max-age=300"
      
      # Upload environment-specific build
      - aws s3 cp dist/keycloak-widget.umd.js s3://$S3_BUCKET/auth/$DEPLOY_ENV/keycloak-widget.umd.js --cache-control "public, max-age=300"
      - aws s3 cp dist/login-widget.css s3://$S3_BUCKET/auth/$DEPLOY_ENV/login-widget.css --cache-control "public, max-age=300"
      
      # Invalidate CloudFront cache if distribution ID is set
      - |
        if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/auth/$DEPLOY_ENV/*" "/auth/latest/*"
        fi
      
      - echo "Deployment completed successfully!"
      - echo "CDN URLs:"
      - echo "  Versioned: https://cdn.bloomelements.com/auth/v$VERSION/keycloak-widget.umd.js"
      - echo "  Latest: https://cdn.bloomelements.com/auth/latest/keycloak-widget.umd.js"
      - echo "  Environment: https://cdn.bloomelements.com/auth/$DEPLOY_ENV/keycloak-widget.umd.js"

artifacts:
  files:
    - dist/keycloak-widget.umd.js
    - dist/login-widget.css
  name: keycloak-widget-$DEPLOY_ENV-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'node_modules/**/*'

reports:
  build-report:
    files:
      - 'build-report.json'
    file-format: 'JUNITXML'
