version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CLI and dependencies..."
      - pip install --upgrade awscli
      
  pre_build:
    commands:
      - echo "Pre-build started on $(date)"
      - echo "AWS CLI version - $(aws --version)"
      - echo "Node version - $(node --version)"
      - echo "NPM version - $(npm --version)"
      - echo "Environment - $ENVIRONMENT"
      - echo "Widget Bucket - $WIDGET_BUCKET_NAME"
      - echo "Distribution ID - $DISTRIBUTION_ID"
      - echo "Configuring CodeArtifact for NPM..."
      - aws codeartifact login --tool npm --repository dev-codeartifact-repository --domain dev-codeartifact-domain --domain-owner $CICD_ACCOUNT_ID --region $AWS_REGION
      - echo "Installing NPM dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building widget for $ENVIRONMENT environment..."
      - npm run build:$ENVIRONMENT || npm run build
      - echo "Build completed successfully"
      - ls -la dist/
      
  post_build:
    commands:
      - echo "Post-build started on $(date)"
      - echo "Deploying to S3 bucket $WIDGET_BUCKET_NAME..."
      - aws s3 sync ./dist s3://$WIDGET_BUCKET_NAME/ --delete --cache-control "max-age=60"
      - echo "S3 deployment completed"
      - echo "Assuming cross-account role for CloudFront invalidation..."
      - eval $(aws sts assume-role --role-arn $CROSS_ACCOUNT_ROLE_ARN --role-session-name codebuild-iam-widget | jq -r '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)"')
      - echo "Creating CloudFront invalidation..."
      - AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'
